// This file is generated

I_short_name_0 = [
"",
"",
"",
"",
"Hansdatter",
"Olafsen, Anders",
"Olesen, Anders",
"Jakobsdatter, Ane",
"Jensdatter, Ane",
"Terkelsdatter, Ane",
"Christensdatter, Ane Cathrine",
"Rasmusdatter, Ane Cathrine",
"Olesdatter, Ane Kirstine",
"Olesen, Ane Kirstine",
"J\u00f8rgensdatter, Anna",
"Pedersen, Anne",
"Rasmusdatter, Anne",
"S\u00f8rensdatter, Anne",
"J\u00f8rgensdatter, Anne",
"S\u00f8rensdatter, Anne Kirstine",
", Annelise",
"Jensen, Anton",
"Hansdatter, Birthe",
"Larsen, Birthe Kirstine",
"Larsen, Birthe Kirstine",
"Andersdatter, Bodil",
"Nielsen, Christen",
"Christensen, Christen",
"Jensen, Christen Hald",
", Elsa",
"Andersdatter, Else Maria",
"Andersdatter, Else Maria",
"Mortensdatter, Gertrud",
"Nielsdatter, Gertrud Maria",
"Larsen, Hans",
"Poulsen, Henrich",
"J\u00f8rgensen, Henrich",
"S\u00f8rensen, Jacob",
"Larsen, Jens",
"Nielsen, Jens Peer Pind",
"Jensen, Jens Peter",
"Pedersdatter, Johanne",
"J\u00f8rgensen, J\u00f8rgen",
"J\u00f8rgendatter, Karen",
"S\u00f8rensdatter, Karen",
"Larsen, Karen",
"Pedersdatter, Karen",
"Hansdatter, Karen",
", Kirsten",
"Rasmusdatter, Kirsten",
"Pedersdatter, Kirsten",
"Nielsdatter, Kirsten",
"Nielsen, Lars",
", Maren",
"Andersdatter, Maren",
"Nielsdatter, Maren",
"J\u00f8rgensdatter, Margrete",
", Margrethe",
"S\u00f8rensdatter, Marie Kathrine",
"Olesdatter, Mette Marie",
"Andersen, Niels",
"Olesen, Niels",
"Olesen, Niels",
"Larsen, Niels",
"Nielsen, Niels",
"Andersen, Niels",
"Rasmussen, Niels",
"Jensen, Niels Madsen",
"Andersen, Ole",
"Jensen, Otto",
"Olesen, Peder",
"Nielsen, Peder",
"Christensen, Rasmus",
"S\u00f8rensen, Rasmus",
"Jensen, Rasmus",
"Jensen, Rasmus",
"Rasmussen, Rasmus",
"Terkelsen, Rasmus",
"Nielsen, Rasmus",
", Sten",
"Thomasen, S\u00f8ren",
"Olesen, S\u00f8ren",
", Terkel",
"S\u00f8rensen, Thomas",
"Adamsen, Peder",
"Adsersen, Bunde",
"Adsersen, Bunde",
"Andersdatter, Ane",
"Andersdatter, Karen",
"Andersdatter, Malene",
"Andersdatter, Maren",
"Andersen, Anders",
"Andersen, Axel Valdemar",
"Andersen, Dorothea",
"Andersen, Else",
"Andersen, Esbern Valdemar",
"Andersen, Grete",
"Andersen, Gunnild",
"Andersen, Hans",
"Andersen, Helge Niels S\u00f8ren",
"Andersen, Jens",
"Andersen, Jens",
"Andersen, Jens",
"Andersen, Johannes",
"Andersen, Joseph",
"Andersen, Lars",
"Andersen, Mona Bune",
"Andersen, Ove Anders",
"Andersen, S\u00f8ren",
"Andersen, S\u00f8ren Christian",
"Andreasdatter, Marina",
"Beicher, Elisabeth Sophie Philipsdatter",
"Bergmann, Doris",
"Bergmann, Eigil",
"Bergmann, Svend Aage Carl",
"Bertelsen, Christen",
"Bjelke",
"Bjelke",
"Bjelke, Ane Hermine Frederikke",
"Bjelke, Anton August",
"Bjelke, Bendix Christensen",
"Bjelke, Christian Peter Theodor",
"Bjelke, Emil Valdemar",
"Bjelke, Emil Waldemar",
"Bjelke, Emma Wilhelmine",
"Bjelke, Frederik Regner",
"Bjelke, H.C Julius",
"Bjelke, Jacobine",
"Bjelke, Jacobine Maria",
"Bjelke, Michael Christensen",
"Bjelke, Peder Henning Bendixen",
"Bjelke, Semine Cecilia Andrea",
"Bjelke, Severin Theodor Eduard",
"Boye, Mads Hansen",
"Br\u00e9sson, Sonja Ida Sofie",
"Bruun, Anne Magdalene Rammine",
"Bruun, Anne Marie Augusta",
"Bruun, Anne Pauline",
"Bruun, Carl Erhard Arnoldus",
"Bruun, Charlotte Amalia Lassen",
"Bruun, Christian",
"Bruun, Christian Friderich",
"Bruun, Christiane Augusta Larsen",
"Bruun, Georg",
"Bruun, Georgine",
"Bruun, J\u00f8rgen Larsen",
"Bruun, Martha Friderica Larsen",
"Buch, Arne",
"Buch, Gudrun",
"Buch, Henning",
"Buch, Jytte",
"Buch, Tove",
"Bundedatter, Mette Marie Adsersdatter",
"Bundesen, Adser",
"Bundesen, Adser",
"Bune, Mary Emma",
"Bune, Sarah Jane",
"Bune, Thomas",
"Christendatter, Ane Cathrine",
"Christendatter, Ane Marie",
"Christendatter, Else Marie",
"Christendatter, Maren",
"Christendatter, Mette Marie",
"Christensdatter, Bodil",
"Christensdatter, Gertrud",
"Christensdatter, Gjertrud",
"Christensdatter, Karen",
"Christensdatter, Karen",
"Christensdatter, Kirstine",
"Christensdatter, Maren",
"Christensen, Agnes Cathrine M\u00f8gelgaard",
"Christensen, Alfred Viktor M\u00f8gelgaard",
"Christensen, Alfred Villy M\u00f8gelgaard",
"Christensen, Asta Hermine M\u00f8gelgaard",
"Christensen, Benny",
"Christensen, Bent Milton M\u00f8gelgaard",
"Christensen, Birgit",
"Christensen, Bo",
"Christensen, Brian",
"Christensen, Bruno",
"Christensen, Christen",
"Christensen, Christen S\u00f8rensen",
"Christensen, Dagmar Vilhemine M\u00f8gelgaard",
"Christensen, Eduard Bernhard M\u00f8gelgaard",
"Christensen, Ellen Marie M\u00f8gelgaard",
"Christensen, Elvira Olivia M\u00f8gelgaard",
"Christensen, Flemming",
"Christensen, Frode",
"Christensen, Henry Emil M\u00f8gelgaard",
"Christensen, Jenny Caroline M\u00f8gelgaard",
"Christensen, Jens",
"Christensen, Jens Christian",
"Christensen, Jens Eduard M\u00f8gelgaard",
"Christensen, John",
"Christensen, Karoline Vilhelmine M\u00f8gelgaard",
"Christensen, Lilly Alexine M\u00f8gelgaard",
"Christensen, Majken",
"Christensen, Mette",
"Christensen, Mette Kirstine",
"Christensen, Michel",
"Christensen, Mira Amalie Steen",
"Christensen, Niels",
"Christensen, Oscar Alfred M\u00f8gelgaard",
"Christensen, Otto Christian M\u00f8gelgaard",
"Christensen, Rasmus",
"Christensen, Rosa Emilie",
"Christensen, Shila",
"Christensen, Silje Steen",
"Christensen, S\u00f8ren Christian",
"Christensen, S\u00f8ren Christian",
"Christensen, Tony",
"Christensen, Ulla Erna M\u00f8gelgaard",
"Christensen, Viggo Oluf M\u00f8gelgaard",
"Christensensdatter, Mette",
"Christophersen, Michel",
"Christophersen, Thomas",
"Cold, Bente",
"Diemer, Anna Mathiessdatter",
"Diemer, Christina Mathiessdatter",
"Diemer, Inge Maria",
"Diemer, Jacob Jensen",
"Diemer, Johannes",
"Diemer, Johannes",
"Diemer, Maria Dorothea",
"Diemer, Maria Mathiessdatter",
"Diemer, Mathies Jacobsen",
"Diemer, Mathies Matthiesen",
"Diemer, Matthias",
"Diemer, Peter",
"Enig, Hilda Agnes Laura Amalie",
"Eskildsdatter, Anna",
"Espersen, Rasmus",
"Frandsdatter, Mette Cathrine",
"Gregersdatter, Johanne",
"Hald, Christen Rasmussen",
"Handskemager, Christen Michelsen",
"Hansdatter, Anne",
"Hansdatter, Bodil",
"Hansdatter, Dorthe",
"Hansdatter, Gertrud",
"Hansdatter, Karen",
"Hansdatter, Karen",
"Hansdatter, Karen",
"Hansdatter, Karen",
"Hansdatter, Karen Kirstine Dam",
"Hansdatter, Kirsten",
"Hansdatter, Maren",
"Hansdatter, Mette",
"Hansen, Anne Marie Dorothea",
"Hansen, Karen",
"Hansen, Marie",
"Hansen, Marinus",
"Hansen, Niels",
"Hansen, Niels",
"Hansen, Niels Kiholm",
"Hansen, Rasmine Nicoline Mathilde",
"Hansen, Rasmus",
"Hendriksen, J\u00f8rgen",
"Hermansdatter, Kirsten Marie",
"Hermansdatter, Maren",
"Hermansen, Iver",
"Hiort, Anne Thomasdatter",
"Hiort, J\u00f8rgen Nielsen",
"Hiort, Niels J\u00f8rgensen",
"Hjort, J\u00f8rgen Nielsen",
"Holm, Karen Marie Magdalene",
"Ipsen, Hans",
"Ivarsdatter, Anne Catrine",
"Iversdatter, Mette Kjerstine Obling",
"Jensdatter, Anna Maria",
"Jensdatter, Birthe",
"Jensdatter, Bodil",
"Jensdatter, Christina",
"Jensdatter, Johanne",
"Jensdatter, Karen",
"Jensdatter, Kiersten",
"Jensdatter, Malene",
"Jensen, Adser",
"Jensen, Anders",
"Jensen, Bodil",
"Jensen, B\u00f8rge Pank",
"Jensen, Gregers",
"Jensen, Hans",
"Jensen, Holger Pank",
"Jensen, Inge Pank",
"Jensen, J\u00f8rgen Pank",
"Jensen, Kirstine Westh",
"Jensen, Knud Pank",
"Jensen, Kurt Pank",
"Jensen, Niels",
"Jensen, Niels Juul Buch",
"Jensen, Ole Pank",
"Jensen, Peder",
"Jepsdatter, Maren",
"Jepsdatter, Maren",
"Joachimsen, Jens",
"Johannsen, Maria Dorothea",
"Josephsen, Anders",
"Josephsen, Anne Marie",
"J\u00f8rgendatter, Maren",
"J\u00f8rgensdatter, Maren",
"J\u00f8rgensen, Ann",
"J\u00f8rgensen, Anne",
"J\u00f8rgensen, Christen",
"J\u00f8rgensen, Frederik",
"J\u00f8rgensen, J\u00f8rgen",
"Kerouedan, Annie",
"Kiholm",
"Kiholm, Ana Catherina Ivarsdatter Christensen",
"Kiholm, Ane Johanne",
"Kiholm, Ane Kirstine",
"Kiholm, Anne Cathrine",
"Kiholm, Anton Christensen",
"Kiholm, Bertel Christensen",
"Kiholm, Christian Hermansen Iversen",
"Kiholm, Gertrud Marie",
"Kiholm, Iver Hermansen Christensen",
"Kiholm, Jens Christensen",
"Kiholm, Jens Jepsen",
"Kiholm, Jens Peder Christensen",
"Kiholm, J\u00f8rgen Christensen",
"Kiholm, Kristen J\u00f8rgensen",
"Kiholm, Mette Marie Christensen",
"Kiholm, Mette Marie Christensen",
"Kiholm, Niels Nielsen Christensen",
"Kiholm, Niels Peter",
"Kikholm, Ane Christensen",
"Kikholm, Hermine Christensen",
"Kirkev\u00e6gter, Anna Elisabeth Bjelke",
"Kirkev\u00e6gter, Severin Bjelke",
"Konge, Ane Marie Christensdatter",
"Konge, Anne Madsdatter",
"Konge, Christen Madsen",
"Konge, Christen S\u00f8rensen",
"Konge, Christen S\u00f8rensen",
"Konge, Christen S\u00f8rensen",
"Konge, Christen S\u00f8rensen",
"Konge, Gjertrud Madsdatter",
"Konge, Gjertrud Madsdatter",
"Konge, Inger S\u00f8rensdatter",
"Konge, Karen Maria S\u00f8rensdatter",
"Konge, Kirsten S\u00f8rensdatter",
"Konge, Mads S\u00f8rensen",
"Konge, Maren S\u00f8rensdatter",
"Konge, Mariane S\u00f8rensdatter",
"Konge, Mariane S\u00f8rensdatter",
"Konge, Mariane S\u00f8rensdatter",
"Konge, Niels Christensen",
"Konge, Niels S\u00f8rensen",
"Konge, Oluf Madsen",
"Konge, Peder S\u00f8rensen",
"Konge, Svend Christian S\u00f8rensen",
"Konge, S\u00f8ren Christensen",
"Konge, S\u00f8ren Christensen",
"Konge, S\u00f8ren Madsen",
"Konge, S\u00f8ren Madsen",
"Konge, Villads Christensen",
"Konge, Villads Christensen",
"Kristensen, Ella Pank",
"Kristensen, Rune Pank",
"Kristensen, Tenna Pank",
"Kristensen, Thor Pank",
"Larsdatter, Mette",
"Larsen, Anton Viggo Westh",
"Larsen, Hans Hjort",
"Larsen, Hansine Henriette",
"Larsen, Jan",
"Larsen, Jens",
"Larsen, Jesper Hjort",
"Larsen, Lars",
"Larsen, Poul",
"Larsen, Svend Aage",
"Larsen, Vibeke",
"Larsen, Aage",
"Laugesen, S\u00f8ren",
"Lauridsdatter, Else",
"Lauridsdatter, Johanne",
"Lauritsdatter, Karen",
"Laursen, Niels",
"Laursen, S\u00f8ren",
"Laursen, S\u00f8ren Peter Anton",
"Lind, Sophie Frederikke",
"Lovett, Danny",
"Lovett, Heidi",
"Lovett, Laura Johanna",
"Lovett, Sara Elisabeth",
"Lund, Esben Refsgaard Trier",
"Lund, Julie Pank Trier",
"Lund, Mads Pank Trier",
"Madsdatter, Anna",
"Madsdatter, Anne Cathrine",
"Madsdatter, Karen",
"Madsdatter, Kirsten",
"Madsdatter, Maren",
"Madsdatter, Mette",
"Madsdatter, Mette",
"Matthiesen, Andreas",
"Matthiesen, Christina Maria",
"Matthiesen, Jens",
"Matthiesen, Maren",
"Matthiesen, Marina",
"Matthiesen, Marina",
"Matthiesen, Matthias",
"Matthiesen, Peter",
"Mikkelsen, J\u00f8rgen",
"minor, Niels J\u00f8rgensen",
"Mortensdatter, Karen",
"Mortensen, Ane Kirstine",
"Mortensen, Frands",
"Ben Moussa, Maceo",
"Ben Moussa, Najib",
"Ben Moussa, Nayel",
"Mygen, Anders S\u00f8rensen",
"M\u00f8gelgaard, Alexine Vilhemine",
"M\u00f8gelgaard, Ane Christendatter",
"M\u00f8gelgaard, Caroline Christine Jensine",
"M\u00f8gelgaard, Christen Jensen",
"M\u00f8gelgaard, Georg Vilhelm",
"M\u00f8gelgaard, Hansine Christine",
"M\u00f8gelgaard, Jens Christen",
"M\u00f8gelgaard, Jens Christensen",
"M\u00f8gelgaard, Jens Christian Christensen",
"M\u00f8gelgaard, Johanne Cathrine",
"M\u00f8gelgaard, Karen Marie",
"M\u00f8gelgaard, Olivia Sophie",
"M\u00f8gelgaard, Victor Emil",
"M\u00f8ller, Hans",
"M\u00f8ller, Laurits Andersen",
"M\u00f8ller, S\u00f8ren Lauritzen",
"Nielsdatter, Ane Marie",
"Nielsdatter, Anne",
"Nielsdatter, Christine",
"Nielsdatter, Gjertrud",
"Nielsdatter, Karen",
"Nielsdatter, Maren",
"Nielsdatter, Margrethe",
"Nielsdatter, Marie",
"Nielsdatter, Marie",
"Nielsdatter, Marin",
"Nielsdatter, Mette",
"Nielsen, Anders",
"Nielsen, Ane Marie",
"Nielsen, Angelika Laura Vivi",
"Nielsen, Anne Marie",
"Nielsen, Axel William",
"Nielsen, Caroline Amalie",
"Nielsen, Christian Bertrand",
"Nielsen, Dagny",
"Nielsen, Else Katrine",
"Nielsen, Hans",
"Nielsen, Helle Pank",
"Nielsen, Karen Kirstine",
"Nielsen, Lars Dencker",
"Nielsen, Laura Kirstine",
"Nielsen, Laura Kirstine",
"Nielsen, Lauritz Christian",
"Nielsen, L\u00e6rke Pank",
"Nielsen, Maren",
"Nielsen, Maren",
"Nielsen, Maren",
"Nielsen, Niels",
"Nielsen, Niels",
"Nielsen, Niels Peder",
"Nielsen, Niels Peder",
"Nielsen, Peder",
"Nielsen, Peder",
"Nielsen, Peder",
"Nielsen, Petra Hansine",
"Nielsen, Rasmus",
"Nielsen, Rikke Pank",
"Oulund, Gertrude Marie Nielsdatter",
"Oulund, Niels Nielsen",
"Oulund, Niels Nielsen",
"Paludan, Anna Sophia",
"Pank, Gitte",
"Pank, Liza",
"Pank, Per",
"Pedersdatter, Anne",
"Pedersdatter, Birthe",
"Pedersen, Anne",
"Pedersen, Brenda Fitzmaurice",
"Pedersen, Caroline Maria Camilla",
"Pedersen, Else Margrethe",
"Pedersen, Hans",
"Pedersen, Hans J\u00f8rgen",
"Pedersen, Karen",
"Pedersen, Kirsten",
"Pedersen, Lauge",
"Pedersen, Otto S\u00f8ren",
"Pedersen, Paula Kirsten Asta",
"Pedersen, Peder",
"Pedersen, Robert Karl Hassenfelder",
"Pedersen, S\u00f8ren",
"Petersdatter, Anna",
"Petersen, Lauritz Christian",
"Poulsen, Leo H.",
"Poulsen, Peter L.",
"Paaskiar, Lars Gregersen",
"Rasmusdatter, Sophia",
"Rasmussen, Hans",
"Rasmussen, Laura Johanne",
"Rasmussen, Laurits",
"Rasmussen, Peder",
"Rasmussen, Peter",
"Rasmussen, Rasmus",
"Richardsen, Peter",
"Riersen, Einar Oluf M\u00f8gelgaard",
"Riersen, Emilie Hansine Vilhelmine",
"Riersen, Peter Emilius",
"Roulund, Lise",
"Roulund, Rasmus Pank",
"Roulund, Thomas Pank",
"Sainsbury, Mary Ann",
"Skiotte, Hans",
"Skov, Caroline Marie Rasmussen",
"Skovenby, Kamma Rita",
"Smed, Theodorus Lauritsen",
"Soetmand, Axiliane Christine",
"Soetmand, Jacob Christopher",
"Sotmand, Marie Christine",
"Steen, Angelica Marie Pedersen",
"Steen, Anna Boserup",
"Steen, Astrid Bune",
"Steen, Bjarne",
"Steen, Bodil",
"Steen, Bodil Christine Pedersen",
"Steen, Bodil Ediht Pedersen",
"Steen, Elly Birtha",
"Steen, Erik Marius Pedersen",
"Steen, Erling Viggo",
"Steen, Francoise",
"Steen, Harald Rasmus Pedersen",
"Steen, Henny Bodil",
"Steen, Herluf Jens Pedersen",
"Steen, Ian",
"Steen, Jens Peder Pedersen",
"Steen, J\u00f8rgen Pedersen",
"Steen, Kasper",
"Steen, Ketty Camilla Pedersen",
"Steen, Kiartan",
"Steen, Kjeld Herman Pedersen",
"Steen, Malene",
"Steen, Mette Trads",
"Steen, Niels J\u00f8rgen Pedersen",
"Steen, Niels J\u00f8rgen Pedersen",
"Steen, Nikolai",
"Steen, Ole Harry Pedersen",
"Steen, Otto B\u00f8rge Pedersen",
"Steen, Rasmus Pedersen",
"Steen, Remo Emil",
"Steen, Ruth Carla Pedersen",
"Steen, S\u00f8ren Trads",
"Steen, Villy J\u00f8rgen Pedersen",
"Steen, Vivi Mette",
"Svendsdatter, Mette",
"S\u00f8rensdatter, Ane",
"S\u00f8rensdatter, Anna Marie",
"S\u00f8rensdatter, Anne",
"S\u00f8rensdatter, Anne",
"S\u00f8rensdatter, Anne",
"S\u00f8rensdatter, Karen",
"S\u00f8rensen, Ane Hansine",
"S\u00f8rensen, Christen",
"S\u00f8rensen, Herman",
"S\u00f8rensen, Rasmus",
"S\u00f8strup, Hans",
"Tambourg, Hans",
"Terschelsdatter, Anne",
"Theodorusdatter, Anne Cathrine",
"Theodorusdatter, Sophie",
"Thomasdatter, Boel",
"Thomasdatter, Ellen",
"Thomasen, Christoffer",
"Thomasen, Jens",
"Thomasen, Oluf",
"Thomasen, Peder",
"Thomassen, Anders",
"Trads, Annette",
"Trads, Else Pank",
"Trads, Lotte",
"Trads, Paul Rosendigger Elmer",
"Trads, S\u00f8ren Frimann",
"Trads, Theresa Frimann",
"Villadsdatter, Maren",
"Villadsen, Marius",
"West, Mariane",
"West, Ole Nielsen",
"Winther, Else Boserup"
]
Dwr.ScriptLoaded('dwr_db_I_short_name_0.js');
