// This file is generated

I_birth_place_0 = [
"",
"",
"",
"",
"",
"",
"Hvilsager, Hvilsager Sogn, S\u00f8nderhals Herred, Randers Amt, Jylland, Danmark",
"Termestrup, Hvilsager Sogn, S\u00f8nderhals Herred, Randers Amt, Jylland, Danmark",
"Hvilsager, Hvilsager Sogn, S\u00f8nderhals Herred, Randers Amt, Jylland, Danmark",
"",
"",
"Termestrup, Hvilsager Sogn, S\u00f8nderhals Herred, Randers Amt, Jylland, Danmark",
"Hvilsager, Hvilsager Sogn, S\u00f8nderhals Herred, Randers Amt, Jylland, Danmark",
"S\u00f8by, Randers Amt, Jylland, Danmark",
"",
"",
"",
"",
"",
"Daugstrup, Hvilsager Sogn, S\u00f8nderhals Herred, Randers Amt, Jylland, Danmark",
"",
"",
"Strandby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"",
"H\u00e5rby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"",
"",
"",
"Hvilsager, Hvilsager Sogn, S\u00f8nderhals Herred, Randers Amt, Jylland, Danmark",
"",
"",
"",
"",
"",
"H\u00e5rby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"Svanninge, Fyn, Danmark",
"",
"",
"",
"",
"",
"Ollerup, Fyn, Danmark",
"",
"Bobjerg, Lunde Sogn, Bester Horne Herred, Ribe Amt, Jylland, Danmark",
"Hvilsager, Hvilsager Sogn, S\u00f8nderhals Herred, Randers Amt, Jylland, Danmark",
"",
"",
"",
"",
"Strandby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"",
"",
"Strandby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"",
"",
"Strandby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"",
"Strandby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"",
"Daugstrup, Hvilsager Sogn, S\u00f8nderhals Herred, Randers Amt, Jylland, Danmark",
"",
"Hvilsager, Hvilsager Sogn, S\u00f8nderhals Herred, Randers Amt, Jylland, Danmark",
"S\u00f8by, Randers Amt, Jylland, Danmark",
"Strandby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"Strandby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"Strandby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"H\u00e5rby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"",
"Daugstrup, Hvilsager Sogn, S\u00f8nderhals Herred, Randers Amt, Jylland, Danmark",
"",
"S\u00f8by, Randers Amt, Jylland, Danmark",
"",
"",
"",
"",
"",
"Strandby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"",
"",
"",
"Tjerrild, Randers Amt, Jylland, Danmark",
"Hvilsager, Hvilsager Sogn, S\u00f8nderhals Herred, Randers Amt, Jylland, Danmark",
"",
"",
"",
"",
"",
"",
"Fausing, Randers Amt, Jylland, Danmark",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Nyborg, Fyn, Danmark",
"Vester Nykirke, Ribe Amt, Jylland, Danmark",
"Vor Frue Kirke, Svendborg, Fyn, Danmark",
"Kerteminde, Fyn, Danmark",
"K\u00f8benhavn, Sj\u00e6lland, Danmark",
"Varde, Jylland, Danmark",
"K\u00f8benhavn, Sj\u00e6lland, Danmark",
"",
"Varde, Jylland, Danmark",
"",
"",
"K\u00f8benhavn, Sj\u00e6lland, Danmark",
"",
"",
"Vester Nykirke, Ribe Amt, Jylland, Danmark",
"Varde, Jylland, Danmark",
"",
"Christianskirken, K\u00f8benhavn, Sj\u00e6lland, Danmark",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Roager",
"",
"",
"",
"Cork, Irland",
"",
"",
"",
"",
"",
"",
"\u00d8ster Alling, \u00d8steralling Sogn, Randers Amt, Jylland, Danmark",
"",
"",
"",
"Espe Sogn, Fyn, Danmark",
"",
"",
"",
"",
"Vor Frelser Sogn, Esbjerg, Ribe Amt, Jylland, Danmark",
"Enghavevej 214 st. tv., Valby Sogn, Valby, K\u00f8benhavn, Sj\u00e6lland, Danmark",
"",
"Enghavevej 214 st. tv., Valby Sogn, Valby, K\u00f8benhavn, Sj\u00e6lland, Danmark",
"",
"",
"",
"",
"",
"",
"",
"Esbjerg Sogn, Ribe Amt, Jylland, Danmark",
"",
"",
"",
"",
"Hedebygade 13A, 4., Kristkirke Sogn, K\u00f8benhavn, Sj\u00e6lland, Danmark",
"",
"",
"",
"",
"",
"",
"Esbjerg Sogn, Ribe Amt, Jylland, Danmark",
"",
"",
"",
"",
"",
"",
"",
"",
"Ollerup, Fyn, Danmark",
"",
"",
"",
"",
"",
"",
"Enghavevej 214 st. tv., Valby Sogn, Valby, K\u00f8benhavn, Sj\u00e6lland, Danmark",
"",
"",
"",
"",
"",
"Store Emmerske, T\u00f8nder Sogn, Nordslesvig",
"",
"",
"",
"",
"",
"",
"",
"",
"Store Emmerske, T\u00f8nder Sogn, Nordslesvig",
"",
"",
"",
"",
"",
"Vesterballe, Ho sogn, Ribe, Ribe Amt, Jylland, Danmark",
"",
"\u00d8ster Alling, \u00d8steralling Sogn, Randers Amt, Jylland, Danmark",
"Kerteminde, Fyn, Danmark",
"",
"",
"Novrup, Jerne, Esbjerg, Ribe Amt, Jylland, Danmark",
"Refsvindinge, Fyn, Danmark",
"",
"",
"",
"",
"",
"",
"",
"",
"Allested",
"H\u00e5strup, Fyn, Danmark",
"Haastrup Sogn, Sallinge Herred, Svendborg Amt",
"",
"",
"H\u00e5rby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"St. Kathrine, Ribe, Ribe Amt, Jylland, Danmark",
"H\u00e5strup, Fyn, Danmark",
"H\u00e5rby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"Ulb\u00f8lle, Fyn, Danmark",
"",
"",
"Roager",
"\u00c5rre, \u00c5rre sogn, Ribe Amt, Jylland, Danmark",
"\u00c5rre, \u00c5rre sogn, Ribe Amt, Jylland, Danmark",
"",
"Sm\u00f8rp\u00f8tte, Jylland, Danmark",
"Jordl\u00f8se, Fyn, Danmark",
"Strandby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"Vodder, T\u00f8nder Amt, Roager Sogn, Haderslev Amt",
"\u00d8ster \u00c5b\u00f8lling, Roager Sogn, Haderslev Amt",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Termestrup, Hvilsager Sogn, S\u00f8nderhals Herred, Randers Amt, Jylland, Danmark",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Store Emmerske, T\u00f8nder Sogn, Nordslesvig",
"",
"",
"Sm\u00f8rp\u00f8tte, Jylland, Danmark",
"",
"",
"",
"",
"",
"",
"",
"Gunderup, \u00c5rre sogn, Ribe Amt, Jylland, Danmark",
"Ribe, Ribe Amt, Jylland, Danmark",
"Gunderup, \u00c5rre sogn, Ribe Amt, Jylland, Danmark",
"Roager",
"Roager Sogn, Haderslev Amt",
"Lustrup, Ribe, Ribe Amt, Jylland, Danmark",
"Roager",
"Roager",
"Lustrup, Ribe, Ribe Amt, Jylland, Danmark",
"Lustrup, Ribe, Ribe Amt, Jylland, Danmark",
"Roager Sogn, Haderslev Amt",
"\u00c5rre, \u00c5rre sogn, Ribe Amt, Jylland, Danmark",
"Lustrup, Ribe, Ribe Amt, Jylland, Danmark",
"\u00c5b\u00f8lling, Roager Sogn, Haderslev Amt",
"Gunderup, \u00c5rre sogn, Ribe Amt, Jylland, Danmark",
"",
"Roager Kirkeby, T\u00f8nder Amt, Roager Sogn, Haderslev Amt",
"Roager Kirkeby, T\u00f8nder Amt, Roager Sogn, Haderslev Amt",
"",
"",
"",
"Nyborg, Fyn, Danmark",
"Nyborg, Fyn, Danmark",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Svanninge, Fyn, Danmark",
"",
"",
"",
"\u00c5rre, \u00c5rre sogn, Ribe Amt, Jylland, Danmark",
"",
"Janderup, Jylland, Danmark",
"Ny M\u00f8lle, Ellested, Fyn, Danmark",
"",
"",
"Kolding, Jylland, Danmark",
"Odense, Fyn, Danmark",
"",
"",
"",
"",
"",
"",
"",
"Kv\u00e6rndrup, Kv\u00e6rndrup Sogn, Svendborg, Fyn, Danmark",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"\u00c5rre, \u00c5rre sogn, Ribe Amt, Jylland, Danmark",
"",
"",
"",
"",
"",
"",
"Fausing, Randers Amt, Jylland, Danmark",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Ny M\u00f8lle, Ellested, Fyn, Danmark",
"",
"",
"Svanninge, Fyn, Danmark",
"",
"",
"",
"",
"",
"",
"",
"Debel, F\u00e5borg, Jylland, Danmark",
"",
"Kahange, Gamtofte Sogn",
"Hasselager, Jylland, Danmark",
"",
"",
"",
"Starup Sogn, Ribe Amt, Jylland, Danmark",
"Starup Sogn, Ribe Amt, Jylland, Danmark",
"",
"",
"",
"",
"Starup Sogn, Ribe Amt, Jylland, Danmark",
"",
"",
"",
"",
"",
"",
"",
"\u00d8se Sogn",
"",
"",
"",
"",
"",
"",
"",
"Strandby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"Strandby, H\u00e5rby Sogn, B\u00e5g Herred, Odense Amt",
"",
"Vester Vedsted, Ribe, Ribe Amt, Jylland, Danmark",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Sankt Hans Sogn, Odense, Fyn, Danmark",
"",
"",
"",
"",
"",
"Vong, Jylland, Danmark",
"",
"\u00d8lsemagle Sogn, Roskilde Amt, Sj\u00e6lland, Danmark",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"N\u00f8rremark, Svanninge Sogn",
"\u00c5rre, \u00c5rre sogn, Ribe Amt, Jylland, Danmark",
"Ellested, Fyn, Danmark",
"Espe, Espe Sogn, Fyn, Danmark",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Newbury, Berkshire, England, UK",
"",
"N\u00f8rup, Vejle, Jylland, Danmark",
"",
"Ellested, Fyn, Danmark",
"",
"",
"",
"Sankt Hans Sogn, Odense, Fyn, Danmark",
"Rosenstykket 14.1, Vanl\u00f8se, K\u00f8benhavn, Sj\u00e6lland, Danmark",
"",
"Amagerbrogade 87, 1.sal, K\u00f8benhavn, Sj\u00e6lland, Danmark",
"Bjelkes Alle 5, N\u00f8rrebro, K\u00f8benhavn, Sj\u00e6lland, Danmark",
"",
"",
"",
"",
"Strandmarks Sogn, Hvidovre, Sokkelund Herred",
"",
"R\u00e5dvad, T\u00e5rb\u00e6k, Sj\u00e6lland, Danmark",
"",
"Korsgade 29B, 1. sal, K\u00f8benhavn, Sj\u00e6lland, Danmark",
"",
"Sankt Knud Sogn, Odense, Fyn, Danmark",
"Bobjerg, Lunde Sogn, Bester Horne Herred, Ribe Amt, Jylland, Danmark",
"",
"J\u00e6gergade 17 st., N\u00f8rrebro, K\u00f8benhavn, Sj\u00e6lland, Danmark",
"",
"",
"",
"",
"Svendborg, Fyn, Danmark",
"Allerup Mark",
"Risbjerg Sogn, Hvidovre, Sokkelund Herred",
"",
"",
"Vor Frue Sogn, Svendborg, Fyn, Danmark",
"Vigerslev Sogn",
"",
"Holb\u00e6k sygehus, Holb\u00e6k, Sj\u00e6lland, Danmark",
"L\u00e6ss\u00f8egade 15.5, Skt. Johannes sogn, K\u00f8benhavn, Sj\u00e6lland, Danmark",
"Strandmarks Sogn, Hvidovre, Sokkelund Herred",
"",
"",
"",
"",
"",
"",
"",
"Gunderup, \u00c5rre sogn, Ribe Amt, Jylland, Danmark",
"",
"",
"N\u00f8rremark, Svanninge Sogn",
"Borgergade 16, Vor Frelser Sogn, Esbjerg, Ribe Amt, Jylland, Danmark",
"",
"",
"",
"Ellested, Fyn, Danmark",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Skt. Johannes kirke, Skt. Johannes sogn, K\u00f8benhavn, Sj\u00e6lland, Danmark",
"",
"",
""
]
Dwr.ScriptLoaded('dwr_db_I_birth_place_0.js');
